module.exports = {
    ALREADY_VERIFIED: "Vec si verificiran!",
    NO_MAIL_INPUT: "Niste upisali svoj email! Upisite ga (!email pero@tvz.hr).",
    WRONG_CONFIRM_CODE: "Krivi potvrdni kod!",
    HELP_MESSAGE: "prefix: !\nnaredba: email [test@tvz.hr] -> za dohvacanje potvrdnog koda na mejl\nnaredba: code [ABCDEFGHIJ] -> za unos koda i zavrsetak verifikacije",
    VERIFICATION_SUCCESSFUL: "Uspjesno si se verificirao/la!",
    INFO_MESSAGE_AFTER_MAIL_SEND: "Poslali smo ti potvrdni kod na mail. Molimo te da ga ovdje upises u formatu:\n```!code ABCDEFGHIJ```",
    WELCOME_MESSAGE: "Dobrodosao na TVZ discord server!\nKako bi mogao pristupiti svim kanalima TVZ servera moras dokazati da si zaista TVZ-ov student.\nUpisi svoju @tvz email adresu u sljedecem formatu:\n```!email pero@tvz.hr```Napomena: u bilo kojem trenutku se mozes vratiti i ponovo upisati istu naredbu ako se prosli put nisi uspio verificirati (posalji !help za dodatne informacije).\n",
    START_VERIFICATION_COMMAND: "email",
    CONFIRM_VERIFICATION_COMMAND: "code",
    DATABASE_COMMAND: "database",
    HELP_COMMAND: "help",
    BOT_START: 'Bot is running!',
    MAIL_SUBJECT: "TVZ discord potvrdni kod",
    MAIL_CONTENT_BEFORE_CONFIRM_CODE: "Vas potvrdni kod je: ",
    MAIL_CONTENT_AFTER_CONFIRM_CODE: "",
    MAIL_PROVIDER: "gmail",
    MAIL_INVALID: "Nisi student TVZ-a!",
    ROOT_FOLDER: ".",
    FORWARD_SLASH: "/",
    BOT_COMMANDS_FOLDER: "bot_commands",
    JMBAG_COMMAND: "jmbag",
    BACKUP_COMMAND: "backup",
    BACKUP_SENT_MESSAGE: "Check bot email!",
    REDOVNI_ROLE: "redovni",
    IZVANREDNI_ROLE: "izvanredni",
    MOD_ROLE: "mod",
    PRIVATE_CHANNEL_TYPE: "dm",
    NO_SUCH_STUDENT_MESSAGE: "Ne postoji student pod tim imenom!",
    VERIFICATION_UNSUCCESSFUL: "Verifikacija neuspjesna! Kontaktirajte admina.",
    MAIL_SENDING_TOO_FAST: "Prebrzo saljes kodove. Probaj ponovo kasnije.",
    SECONDS_TIMEOUT_MAIL_SENDING: 300,
    USER_NOT_ON_SERVER_MESSAGE: "Nema te na serveru. Moras biti prisutan na serveru kako bi koristio bota!",
    BOT_COMMANDS_DIRECTORY: "./bot_commands/",
};